name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to Hugging Face
        uses: backendcloud/hugging-push@v0.2.3
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_id: ggSOS/Sistema_Inteligente_de_Controle_de_Gastos
          repo_type: space
          space_sdk: gradio
