name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync with Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ggSOS/Sistema_Inteligente_de_Controle_de_Gastos
          huggingface_repo_id: ggSOS/Sistema_Inteligente_de_Controle_de_Gastos
          repo_type: space
          space_sdk: gradio
          hf_token: ${{ secrets.HF_TOKEN }}
          private: false
